#!/usr/bin/python
"""remad -- remadd (remctl admin tool) client"""

import argparse
import base64
import logging
import os
import socket
import subprocess
import sys





class Remad(object):
	"""remad client class"""

	def __init__(self, server):
		self.log = logging.getLogger()
		self.server = server



	def remctlcall(self, cmd):
		"""wraps command with remctl client call and executes"""

		cmd = ["/usr/bin/remctl", self.server, "remadd"] + cmd
		proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
		(proc_stdout, proc_stderr) = proc.communicate()
		return (proc, proc_stdout, proc_stderr)



	def createkeytab(self, host, services, outfile):
		"""creates keytab for services/host to outfile"""

		cmd = ["createkeytab", "--host", host, "--services"] + services
		(proc, proc_stdout, proc_stderr) = self.remctlcall(cmd)
		sys.stderr.write(proc_stderr)

		# data of created keytab are transfered via stdout encoded in base64
		self._write_outfile(outfile, base64.b64decode(proc_stdout))
		self.log.debug("keytab for %s created in %s", host, outfile)

		return proc.returncode



	def storesshhostkey(self, host, filename):
		"""stores filename for host at keyserver"""

		# getconf ARG_MAX, xargs --show-limits, base64 encoding
		filesize = os.stat(filename).st_size
		self.log.debug("stored filesize %d", filesize)
		if filesize > 98000:
			raise Exception("file too big for remctl transfer")

		with open(filename, "r") as ftmp:
			data = base64.b64encode(ftmp.read())

		cmd = ["storesshhostkey", "--host", host, "--filename", os.path.basename(filename), "--data", data]
		(proc, proc_stdout, proc_stderr) = self.remctlcall(cmd)
		sys.stderr.write(proc_stderr)
		sys.stdout.write(proc_stdout)
		self.log.debug("file %s stored for %s", filename, host)

		return proc.returncode



	def getsshhostkey(self, host, filename, outfile):
		"""retrieves filename for host from keyserver"""

		cmd = ["getsshhostkey", "--host", host, "--filename", filename]
		(proc, proc_stdout, proc_stderr) = self.remctlcall(cmd)
		sys.stderr.write(proc_stderr)

		if proc.returncode == 0:
			self._write_outfile(outfile, base64.b64decode(proc_stdout))
			self.log.debug("file %s for %s created in %s", filename, host, outfile)

		return proc.returncode



	def getknownhosts(self, outfile):
		"""generates global ssh_known_hosts file from keystorage"""

		cmd = ["getknownhosts"]
		(proc, proc_stdout, proc_stderr) = self.remctlcall(cmd)
		sys.stderr.write(proc_stderr)

		if proc.returncode == 0:
			self._write_outfile(outfile, base64.b64decode(proc_stdout))
			self.log.debug("known_hosts file created in %s", outfile)

		return proc.returncode



	@staticmethod
	def _write_outfile(outfile, data):
		if outfile == "-":
			ftmp = sys.stdout
		else:
			ftmp = open(outfile, "w")
		ftmp.write(data)
		ftmp.close()



def parse_arguments():
	"""parses command line arguments"""

	parser = argparse.ArgumentParser()
	parser.add_argument("--server", default=socket.getfqdn(), help="remctladmd server")
	parser.add_argument("--debug", action="store_true", default=False, help="debug output")

	subparsers = parser.add_subparsers(dest='command')

	parser_createkeytab = subparsers.add_parser("createkeytab", help="createkeytab command help")
	parser_createkeytab.add_argument("--host", required=True, help="create (upsert principals) keytab for hostname")
	parser_createkeytab.add_argument("--services", required=True, nargs="+", help="create (upsert principals) keytab for services at hostname")
	parser_createkeytab.add_argument("--outfile", required=True, help="write created keytab to file")

	parser_storesshhostkey = subparsers.add_parser("storesshhostkey", help="storesshhostkey command help")
	parser_storesshhostkey.add_argument("--host", required=True, help="hostname to store key for")
	parser_storesshhostkey.add_argument("--filename", required=True, help="filepath")

	parser_getsshhostkey = subparsers.add_parser("getsshhostkey", help="getsshhostkey command help")
	parser_getsshhostkey.add_argument("--host", required=True, help="get file for hostname")
	parser_getsshhostkey.add_argument("--filename", required=True, help="filename to get from storage")
	parser_getsshhostkey.add_argument("--outfile", required=True, help="write fetched file to path")

	parser_getknownhosts = subparsers.add_parser("getknownhosts", help="getknownhosts command help")
	parser_getknownhosts.add_argument("--outfile", required=True, help="write fetched file to path")

	return parser.parse_args()



def main():
	"""main"""

	logging.basicConfig(level=logging.INFO, format=os.path.basename(sys.argv[0])+'[%(process)d] %(levelname)s %(message)s')
	args = parse_arguments()
	if args.debug:
		logging.basicConfig(level=logging.DEBUG)


	remad = Remad(args.server)
	if args.command == "createkeytab":
		ret = remad.createkeytab(args.host, args.services, args.outfile)
	elif args.command == "storesshhostkey":
		ret = remad.storesshhostkey(args.host, args.filename)
	elif args.command == "getsshhostkey":
		ret = remad.getsshhostkey(args.host, args.filename, args.outfile)
	elif args.command == "getknownhosts":
		ret = remad.getknownhosts(args.outfile)
	else:
		ret = 127

	return ret



if __name__ == "__main__":
	sys.exit(main())
